// generated by build.rs -- don't edit directly

mod year2015 {
    pub mod day01;
    pub mod day02;
    pub mod day03;
    pub mod day04;
    pub mod day05;
    pub mod day06;
    pub mod day07;
}

use std::collections::BTreeMap;

pub struct Solution {
    pub part1: Option<fn(&str) -> String>,
    pub part2: Option<fn(&str) -> String>,
    pub tests: Option<fn() -> ()>,
}

pub fn build() -> BTreeMap<u16, BTreeMap<u8, Solution>> {
    let mut solutions: BTreeMap<u16, BTreeMap<u8, Solution>> = BTreeMap::new();

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        1,
        Solution {
            part1: Some(|input| year2015::day01::part1(input).to_string()),
            part2: Some(|input| year2015::day01::part2(input).to_string()),
            tests: Some(year2015::day01::tests),
        },
    );

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        2,
        Solution {
            part1: Some(|input| year2015::day02::part1(input).to_string()),
            part2: Some(|input| year2015::day02::part2(input).to_string()),
            tests: None,
        },
    );

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        3,
        Solution {
            part1: Some(|input| year2015::day03::part1(input).to_string()),
            part2: Some(|input| year2015::day03::part2(input).to_string()),
            tests: Some(year2015::day03::tests),
        },
    );

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        4,
        Solution {
            part1: Some(|input| year2015::day04::part1(input).to_string()),
            part2: Some(|input| year2015::day04::part2(input).to_string()),
            tests: Some(year2015::day04::tests),
        },
    );

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        5,
        Solution {
            part1: Some(|input| year2015::day05::part1(input).to_string()),
            part2: Some(|input| year2015::day05::part2(input).to_string()),
            tests: Some(year2015::day05::tests),
        },
    );

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        6,
        Solution {
            part1: Some(|input| year2015::day06::part1(input).to_string()),
            part2: Some(|input| year2015::day06::part2(input).to_string()),
            tests: None,
        },
    );

    solutions.entry(2015).or_insert_with(BTreeMap::new).insert(
        7,
        Solution {
            part1: Some(|input| year2015::day07::part1(input).to_string()),
            part2: Some(|input| year2015::day07::part2(input).to_string()),
            tests: Some(year2015::day07::tests),
        },
    );

    solutions
}
