// generated by build.rs -- don't edit directly

mod year2015 {
    pub mod day01;
}

use std::collections::HashMap;

pub struct Solution {
    pub part1: Option<fn(&str) -> String>,
    pub part2: Option<fn(&str) -> String>,
    pub tests: Option<fn() -> ()>,
}

pub fn build() -> HashMap<u16, HashMap<u8, Solution>> {
    let mut solutions: HashMap<u16, HashMap<u8, Solution>> = HashMap::new();

    solutions.entry(2015).or_insert_with(HashMap::new).insert(
        1,
        Solution {
            part1: Some(|input| year2015::day01::part1(input).to_string()),
            part2: Some(|input| year2015::day01::part2(input).to_string()),
            tests: Some(year2015::day01::tests),
        },
    );

    solutions
}
